[workspace]
members = ["astrorust_app", "astrorust_gui_lib", "astrorust_lib"]
resolver = "3"

[workspace.dependencies]
kiss3d = { version = "0.37.2", default-features = false }

# Fork making the `image` dependency optional
[patch.crates-io]
kiss3d = { git = "https://github.com/Logarithmus/kiss3d", branch = "image-optional" }

[profile.bench]
lto = "thin"

