[package]
name = "AstroGraphicRust"
version = "0.1.0"
authors = ["gdck"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.28"
nalgebra = "*"
