unstable_features = true
tab_spaces = 4
hard_tabs = true
reorder_impl_items = true
reorder_imports = false
newline_style = "Unix"
imports_granularity = "Crate"
use_field_init_shorthand = true
use_small_heuristics = "Max"
